---
title: "CSC/SCI 230: Data Science 1"
---

Instructor: Kayla Blincow, PhD (aka Kayla Israel)

------------------------------------------------------------------------

# Welcome!

This website houses all of the coding exercises and assignments for CSC/SCI 230 Data Science 1. All other course documentation can be found on Brightspace.

# Schedule

|        Week         |     Dates     |                   Materials                    |
|:-------------------:|:----------------:|:--------------------------------:|
|          1          |  8/19 - 8/23  |          [Homework 1](Week1R4DS.qmd)           |
|          2          |  8/26 - 8/30  |           [Homework 2](Week2HW.qmd)            |
|          3          |   9/3 - 9/6   |           [Homework 3](Week3HW.qmd)            |
|          4          |  9/9 - 9/13   |           [Homework 4](Week4HW.qmd)            |
|          5          |  9/16 - 9/20  |           [Homework 5](Week5HW.qmd)            |
|          6          |  9/23 - 9/27  |           [Homework 6](Week6HW.qmd)            |
|          7          |  9/30 - 10/4  |           [Homework 7](Week7HW.qmd)            |
|          8          | 10/7 - 10/11  |           [Homework 8](Week8HW.qmd)            |
|          9          | 10/14 - 10/18 |           [Homework 9](Week9HW.qmd)            |
|         10          | 10/21 - 10/25 |          [Homework 10](Week10HW.qmd)           |
|         11          | 10/28 - 10/31 |          [Homework 11](Week11HW.qmd)           |
|         12          |  11/4 - 11/8  |          [Homework 12](Week12HW.qmd)           |
|         13          | 11/12 - 11/15 |          [Homework 13](Week13HW.qmd)           |
|         14          | 11/18 - 11/22 |          [Homework 14](Week14HW.qmd)           |
|         15          | 11/25 - 11/26 |          [Homework 15](Week15HW.qmd)           |
| URISE DS Wksp Day 1 |     8/28      |       [DS Wksp Tutorial 1](DSWksp1.qmd)        |
| URISE DS Wksp Day 2 |      9/4      |       [DS Wksp Tutorial 2](DSWksp2.qmd)        |
| URISE DS Wksp Day 3 |      9/8      |       [DS Wksp Tutorial 3](DSWksp3.qmd)        |
| 2 (Vis Accessible)  |  8/26 - 8/30  | [Homework 2 (Vis Accessible)](Week2HW_VA.qmd)  |
